# Generated by Django 5.2.4 on 2026-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField(max_length=10)),
                ('weight', models.IntegerField(max_length=10)),
                ('food', models.CharField(max_length=100)),
                ('meal', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now=True)),
                ('updated_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
