# Generated by Django 5.2.4 on 2026-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0002_alter_meal_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='name_1',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility')], max_length=20),
        ),
    ]
