# Generated by Django 5.2.4 on 2026-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0003_rename_name_1_fooditem_name_alter_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(help_text='Calculated calories'),
        ),
    ]
