# Generated by Django 5.2.4 on 2026-01-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0004_alter_foodlog_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='calories',
            field=models.FloatField(editable=False),
        ),
    ]
