# Generated by Django 5.2.4 on 2026-01-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0005_alter_foodlog_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.FloatField(editable=False),
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_target', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutri_app.userprofile')),
            ],
        ),
    ]
